### PR TITLE
Various minor bug fixes and improvements.

### PR DESCRIPTION
**Pull request by puttydotexe**
These commits fix minor bugs and add improvements to the Leap system.

### CODE REVIEW

**Comment by puttydotexe** [comment]
Leap's code is setup to read certain manifest values, it doesn't however include them all. such "server_scripts" rather than "server_script". I wasn't sure if this was designed in this manner for a reason so rather than adding the additional entries hard defined, I added them into a configurable format. I'm also using it as a workaround for globbing not being detected.

**Comment by XenoS-ITA** [comment]
server_script also includes server_scripts, probably below server_scripts actually gets converted to multiple server_script calls.
The only thing to remove to the pull request is the directories hardly set in the config, since they don't make too much sense after multi globbing is fixed

**Comment by puttydotexe** [comment]
It would appear that the manifest issue stemmed from the globbing issue, which has now been resolved.

**Comment by XenoS-ITA** [comment]
Ok strange, can i merge the pull request or you want to edit anything else?

**Comment by puttydotexe** [comment]
Not to my knowledge, I'll open further pull requests if required.

**Comment by XenoS-ITA** [comment]
now should be better, i will merge it when im at home

**Pull request merged**
